@include('layouts.head')
<!-- Page Preloder -->
@include('layouts.header')
@include('layouts.about')
@include('layouts.counter')
@include('layouts.event')
@include('layouts.features')
@include('layouts.team')
@include('layouts.gallery')
@include('layouts.pricing')
@include('layouts.client')
@include('layouts.contact')
@include('layouts.footer')
@include('layouts.scripts')
